steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'asia-south1-docker.pkg.dev/project-2d37241a-3276-4c0d-b31/auralis/governance:latest'
      - '-f'
      - 'kirana_kart/Dockerfile'
      - 'kirana_kart/'

images:
  - 'asia-south1-docker.pkg.dev/project-2d37241a-3276-4c0d-b31/auralis/governance:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
