steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'asia-south1-docker.pkg.dev/project-2d37241a-3276-4c0d-b31/auralis/governance:latest'
      - '-f'
      - 'kirana_kart/Dockerfile'
      - 'kirana_kart/'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/project-2d37241a-3276-4c0d-b31/auralis/governance:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'governance'
      - '--image=asia-south1-docker.pkg.dev/project-2d37241a-3276-4c0d-b31/auralis/governance:latest'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--update-secrets=FRONTEND_URL=auralis-frontend-url:latest'
      - '--quiet'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: LEGACY
